[package]

name = "rustfft"
version = "1.0.1"
authors = ["Allen Welkie <allen.welkie at gmail>"]

description = "A mixed-radix FFT library."
repository = "https://github.com/awelkie/RustFFT"
keywords = ["fft", "dft", "fourier", "signal"]
license = "MIT OR Apache-2.0"

[dependencies]
num = "*"

[dev-dependencies]
rand = "*"
