[package]

name = "rustfft"
version = "1.0.0"
authors = ["Allen Welkie <allen.welkie at gmail>"]

description = "A mixed-radix FFT library."
repository = "https://github.com/awelkie/RustFFT"
keywords = ["fft", "dft", "fourier", "signal"]
license = "MIT"

[features]
# Enable to run benchmarks (requires nightly rust).
bench = []

[dependencies]
num = "*"

[dev-dependencies]
rand = "*"

[dev-dependencies.kissfft]
path = "rust-kissfft"
version = "0.0.8"
