[package]

name = "rustfft"
version = "0.0.2"
authors = ["Allen Welkie <allen.welkie at gmail>"]

description = "A mixed-radix FFT library written in pure Rust"
repository = "https://github.com/awelkie/RustFFT"
keywords = ["fft", "dft", "fourier", "signal"]
license = "MIT"

[dependencies]
num = "*"

[dev-dependencies]
rand = "0.2.0"

[dev-dependencies.kissfft]
path = "rust-kissfft"
