[package]

name = "rustfft"
version = "2.0.0"
authors = ["Allen Welkie <allen.welkie at gmail>"]

description = "A mixed-radix FFT library."
repository = "https://github.com/awelkie/RustFFT"
keywords = ["fft", "dft", "fourier", "signal"]
license = "MIT OR Apache-2.0"

[dependencies]
num-complex = "0.1.36"
num-traits = "0.1.37"

[dev-dependencies]
rand = "0.3.15"
